name: Fetch Arxiv CV 3D Papers

on:
  schedule:
    - cron: '7 4 * * *'  # runs daily at 4:07 UTC
  workflow_dispatch:      # allow manual run from GitHub Actions tab

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
      with:
        persist-credentials: true

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install arxiv openai pydantic jinja2 markdown pdf2image pypdf

    - name: Run the fetch script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SMTP_SERVER: smtp.163.com
        SMTP_PORT: 465
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: |
        python fetch_cv_3d_papers.py

    - name: Commit README changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git stash
        git pull
        git stash pop
        git add README.md
        git commit -m "Update README with new 3D-related papers"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref }}
      continue-on-error: true  # in case there's no change, don't fail the job
